export const ImagePath = {
    boimela_icon: require('../assets/Images/boimela_icon.png'),
    boimela_logo: require('../assets/Images/boimela_logo.png'),
    menu: require('../assets/Images/menu.png'),
    no_image: require('../assets/Images/no_image.png'),
    cart: require('../assets/Images/cart.png'),
    user: require('../assets/Images/user.png'),
    eye_off: require('../assets/Images/eye_off.png'),
    eye_on: require('../assets/Images/eye_on.png'),
    delete: require('../assets/Images/delete.png'),
    back: require('../assets/Images/back.png'),
    search: require('../assets/Images/search.png'),
    right_arrow: require('../assets/Images/right_arrow.png'),
    share: require('../assets/Images/share.png'),
    user_new: require('../assets/Images/user_new.png'),
    logout: require('../assets/Images/logout.png'),
    coupon: require('../assets/Images/coupon.png'),
    lock: require('../assets/Images/lock.png'),
    order: require('../assets/Images/order.png'),
    address: require('../assets/Images/address.png'),
    home: require('../assets/Images/home.png'),
    right_arrow2: require('../assets/Images/right_arrow2.png'),
    login: require('../assets/Images/login.png'),
    refund: require('../assets/Images/refund.png'),
    conditionof_use: require('../assets/Images/conditionof_use.png'),
    privacy_policy: require('../assets/Images/privacy_policy.png'),
    shipping_info: require('../assets/Images/shipping_info.png'),
    about_us: require('../assets/Images/about_us.png'),
    whatsapp:require('../assets/Images/whatsapp.png'),
    call:require('../assets/Images/call.png'),
    email:require('../assets/Images/email.png'),
    banner:require('../assets/Images/banner.jpg')

}